name: PlutoFramework NuGet publish

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  publish-plutoframework:
    env:
      BUILD_CONFIG: 'Release'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup multiple .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.302

    - name: Add MSBuild to PATH (Windows)
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Install .NET MAUI Workloads (Android)
      run: dotnet workload install maui-android --version 9.0.100

    - name: Install .NET MAUI Workloads (iOS)
      run: dotnet workload install maui-ios --version 9.0.100
      
    - name: Restore .NET Workloads
      run: dotnet workload restore PlutoFramework.sln
      
    - name: Restore dependencies
      run: dotnet restore PlutoFramework.sln

    - name: Build
      run: msbuild /t:build,pack /p:Configuration=Release PlutoFramework/PlutoFramework.csproj
    
    - name: Publish PlutoFramework
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
       PROJECT_FILE_PATH: ./PlutoFramework/PlutoFramework.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 

    - name: Publish XcavateSubquery
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PACKAGE_NAME: XcavateSubquery
        PROJECT_FILE_PATH: ./Indexers/XcavateSubquery/XcavateSubquery.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
    
    - name: Publish UniqueryPlus
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PACKAGE_NAME: UniqueryPlus
        PROJECT_FILE_PATH: ./UniqueryPlus/UniqueryPlus.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
